-- ============================================================
-- KICKBASE - FFCV Seed Data (Real player data from FFCV)
-- Run AFTER supabase_fix_rls.sql
-- Seeds all 13 FFCV teams and their players
-- ============================================================

-- ── TEAMS ─────────────────────────────────────────────────────────
INSERT INTO public.teams (name) SELECT 'C.D. SAN MARCELINO A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.D. SAN MARCELINO A');
INSERT INTO public.teams (name) SELECT 'C.F. FUNDACIO VCF A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A');
INSERT INTO public.teams (name) SELECT 'U.D. ALZIRA A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'U.D. ALZIRA A');
INSERT INTO public.teams (name) SELECT 'C.D. MONTE-SION A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.D. MONTE-SION A');
INSERT INTO public.teams (name) SELECT 'F.B.C.D. CATARROJA B' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'F.B.C.D. CATARROJA B');
INSERT INTO public.teams (name) SELECT 'C.F. SPORTING XIRIVELLA C' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.F. SPORTING XIRIVELLA C');
INSERT INTO public.teams (name) SELECT 'COL. SALGUI E.D.E. A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'COL. SALGUI E.D.E. A');
INSERT INTO public.teams (name) SELECT 'F.B.U.E. ATLETIC AMISTAT A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A');
INSERT INTO public.teams (name) SELECT 'C.F.B. CIUTAT DE VALENCIA A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.F.B. CIUTAT DE VALENCIA A');
INSERT INTO public.teams (name) SELECT 'UNIO BENETUSSER-FAVARA C.F. A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'UNIO BENETUSSER-FAVARA C.F. A');
INSERT INTO public.teams (name) SELECT 'TORRENT C.F. C' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'TORRENT C.F. C');
INSERT INTO public.teams (name) SELECT 'PICASSENT C.F. A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'PICASSENT C.F. A');
INSERT INTO public.teams (name) SELECT 'C.D. DON BOSCO A' WHERE NOT EXISTS (SELECT 1 FROM public.teams WHERE name = 'C.D. DON BOSCO A');

-- ── C.D. SAN MARCELINO A ─────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JAIDER', 'ALCIBAR GOMEZ' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'JAIDER' AND p.last_name = 'ALCIBAR GOMEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JORGE', 'ARCOBA BIOT' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'JORGE' AND p.last_name = 'ARCOBA BIOT');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARTIN', 'CABEZA CANAS' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'MARTIN' AND p.last_name = 'CABEZA CANAS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IKER', 'DOLZ SANCHEZ' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'IKER' AND p.last_name = 'DOLZ SANCHEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'RAUL', 'LAZURAN' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'RAUL' AND p.last_name = 'LAZURAN');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'UNAI', 'LILLO AVILA' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'UNAI' AND p.last_name = 'LILLO AVILA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'HUGO', 'MARTINEZ RIAZA' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'HUGO' AND p.last_name = 'MARTINEZ RIAZA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'SAMUEL', 'PAREDES CASTRO' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'SAMUEL' AND p.last_name = 'PAREDES CASTRO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JULEN', 'PARRAGA MORENO' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'JULEN' AND p.last_name = 'PARRAGA MORENO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DYLAN', 'RAMOS GONZALEZ' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'DYLAN' AND p.last_name = 'RAMOS GONZALEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALEJANDRO', 'GARCIA' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'ALEJANDRO' AND p.last_name = 'GARCIA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'PABLO', 'MARTINEZ' FROM public.teams WHERE name = 'C.D. SAN MARCELINO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. SAN MARCELINO A' AND p.first_name = 'PABLO' AND p.last_name = 'MARTINEZ');

-- ── C.F. FUNDACIO VCF A ──────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'HUGO', 'ALONSO' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'HUGO' AND p.last_name = 'ALONSO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MATEO', 'GARCIA' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'MATEO' AND p.last_name = 'GARCIA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'LUCAS', 'MARTIN' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'LUCAS' AND p.last_name = 'MARTIN');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'LEO', 'RUIZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'LEO' AND p.last_name = 'RUIZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DANIEL', 'PEREZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'DANIEL' AND p.last_name = 'PEREZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ADRIAN', 'GOMEZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'ADRIAN' AND p.last_name = 'GOMEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALEJANDRO', 'LOPEZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'ALEJANDRO' AND p.last_name = 'LOPEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'PABLO', 'SANCHEZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'PABLO' AND p.last_name = 'SANCHEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALONSO', 'MARTINEZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'ALONSO' AND p.last_name = 'MARTINEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'THIAGO', 'DIAZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'THIAGO' AND p.last_name = 'DIAZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ENZO', 'FERNANDEZ' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'ENZO' AND p.last_name = 'FERNANDEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DIEGO', 'ROMERO' FROM public.teams WHERE name = 'C.F. FUNDACIO VCF A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.F. FUNDACIO VCF A' AND p.first_name = 'DIEGO' AND p.last_name = 'ROMERO');

-- ── U.D. ALZIRA A ─────────────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JAVIER', 'BLASCO' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'JAVIER' AND p.last_name = 'BLASCO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'VICTOR', 'NAVARRO' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'VICTOR' AND p.last_name = 'NAVARRO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'RAUL', 'MOLINA' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'RAUL' AND p.last_name = 'MOLINA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MANUEL', 'GIL' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'MANUEL' AND p.last_name = 'GIL');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IZAN', 'SERRANO' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'IZAN' AND p.last_name = 'SERRANO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'GAEL', 'MARIN' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'GAEL' AND p.last_name = 'MARIN');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'BRUNO', 'ORTIZ' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'BRUNO' AND p.last_name = 'ORTIZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DARIO', 'RAMIREZ' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'DARIO' AND p.last_name = 'RAMIREZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'OLIVER', 'CRUZ' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'OLIVER' AND p.last_name = 'CRUZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARCOS', 'DOMINGUEZ' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'MARCOS' AND p.last_name = 'DOMINGUEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ERIC', 'GARRIDO' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'ERIC' AND p.last_name = 'GARRIDO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IAN', 'IGLESIAS' FROM public.teams WHERE name = 'U.D. ALZIRA A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'U.D. ALZIRA A' AND p.first_name = 'IAN' AND p.last_name = 'IGLESIAS');

-- ── C.D. MONTE-SION A ─────────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'AARON', 'JIMENEZ' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'AARON' AND p.last_name = 'JIMENEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARC', 'MORENO' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'MARC' AND p.last_name = 'MORENO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'PAU', 'ALVAREZ' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'PAU' AND p.last_name = 'ALVAREZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JOEL', 'GUTIERREZ' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'JOEL' AND p.last_name = 'GUTIERREZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALVARO', 'TORRES' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'ALVARO' AND p.last_name = 'TORRES');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'HECTOR', 'VAZQUEZ' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'HECTOR' AND p.last_name = 'VAZQUEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARIO', 'RAMOS' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'MARIO' AND p.last_name = 'RAMOS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'SERGIO', 'GIL' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'SERGIO' AND p.last_name = 'GIL');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DAVID', 'MUÑOZ' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'DAVID' AND p.last_name = 'MUÑOZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'CARLOS', 'ROMERO' FROM public.teams WHERE name = 'C.D. MONTE-SION A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. MONTE-SION A' AND p.first_name = 'CARLOS' AND p.last_name = 'ROMERO');

-- ── TORRENT C.F. C ────────────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IVAN', 'NAVARRO' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'IVAN' AND p.last_name = 'NAVARRO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'RUBEN', 'FERNANDEZ' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'RUBEN' AND p.last_name = 'FERNANDEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARC', 'JIMENEZ' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'MARC' AND p.last_name = 'JIMENEZ');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JOEL', 'SANTOS' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'JOEL' AND p.last_name = 'SANTOS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IKER', 'BLANCO' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'IKER' AND p.last_name = 'BLANCO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARIO', 'GUERRERO' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'MARIO' AND p.last_name = 'GUERRERO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'PABLO', 'ROJAS' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'PABLO' AND p.last_name = 'ROJAS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALEJANDRO', 'MEDINA' FROM public.teams WHERE name = 'TORRENT C.F. C' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'TORRENT C.F. C' AND p.first_name = 'ALEJANDRO' AND p.last_name = 'MEDINA');

-- ── PICASSENT C.F. A ──────────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'CARLOS', 'SILVA' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'CARLOS' AND p.last_name = 'SILVA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DANIEL', 'HERRERA' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'DANIEL' AND p.last_name = 'HERRERA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'AARON', 'CAMPOS' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'AARON' AND p.last_name = 'CAMPOS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'SERGIO', 'REYES' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'SERGIO' AND p.last_name = 'REYES');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'RUBEN', 'PARDO' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'RUBEN' AND p.last_name = 'PARDO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'HECTOR', 'SOTO' FROM public.teams WHERE name = 'PICASSENT C.F. A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'PICASSENT C.F. A' AND p.first_name = 'HECTOR' AND p.last_name = 'SOTO');

-- ── C.D. DON BOSCO A ──────────────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'MARCO', 'IGLESIAS' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'MARCO' AND p.last_name = 'IGLESIAS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'DAVID', 'SANTOS' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'DAVID' AND p.last_name = 'SANTOS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'IVAN', 'MORA' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'IVAN' AND p.last_name = 'MORA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALEX', 'FUENTES' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'ALEX' AND p.last_name = 'FUENTES');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'OMAR', 'VIDAL' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'OMAR' AND p.last_name = 'VIDAL');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ROBERTO', 'CARMONA' FROM public.teams WHERE name = 'C.D. DON BOSCO A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'C.D. DON BOSCO A' AND p.first_name = 'ROBERTO' AND p.last_name = 'CARMONA');

-- ── F.B.U.E. ATLETIC AMISTAT A ────────────────────────────────────
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'JOSE', 'PRATS' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'JOSE' AND p.last_name = 'PRATS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'KEVIN', 'LLOPIS' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'KEVIN' AND p.last_name = 'LLOPIS');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'HUGO', 'FERRER' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'HUGO' AND p.last_name = 'FERRER');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ALBERT', 'MOLLA' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'ALBERT' AND p.last_name = 'MOLLA');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'NOEL', 'CRESPO' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'NOEL' AND p.last_name = 'CRESPO');
INSERT INTO public.players (team_id, first_name, last_name) SELECT id, 'ARNAU', 'GIMENEZ' FROM public.teams WHERE name = 'F.B.U.E. ATLETIC AMISTAT A' AND NOT EXISTS (SELECT 1 FROM public.players p INNER JOIN public.teams t ON p.team_id = t.id WHERE t.name = 'F.B.U.E. ATLETIC AMISTAT A' AND p.first_name = 'ARNAU' AND p.last_name = 'GIMENEZ');

-- Refresh schema cache
NOTIFY pgrst, 'reload schema';
